### PR TITLE
added search to deals

### PR DESCRIPTION
**Pull request by alexmolinatechconsulting**
added search capability to deals

### CODE REVIEW

**Review by jdemaagd — COMMENTED** [review]
have you tested on an emulator/device?

**Comment by alexmolinatechconsulting** [comment]
> have you tested on an emulator/device?

yes I have

**Review by jdemaagd — COMMENTED** [review]
it doesn't build, 
previous changes had price and title on top/under each other
and image isn't loading
I don't see any changes that would have changed that

**Comment by alexmolinatechconsulting** [comment]
> it doesn't build, previous changes had price and title on top/under each other and image isn't loading I don't see any changes that would have changed that

yeah this fixed all those issue, ill check it out by deleting redownloading

**Review by alexmolinatechconsulting — COMMENTED** [review]
I accidentally pushed a tainted commit commit to the PR, and im going to undo it, but the prior issue with the PR is that I chose the wrong import when resolving conflict

**Pull request closed without merging**
